export const CONFIG = {
  PANEL_WIDTH_MM: 496,
  PANEL_HEIGHT_MM: 496,
  PANEL_PIXELS_W: 192,
  PANEL_PIXELS_H: 192,
  PIXEL_PITCH: "P2.5",
  PANEL_WEIGHT_KG: 10,
  PANEL_POWER_W: 150,
  VOLTAGE: 240,
  PROCESSOR_MAX_PIXELS_W: 1920,
  PROCESSOR_MAX_PIXELS_H: 1080,
  PANELS_PER_DATA_LINE: 13,
  // 13A circuit at 240V with 0.8 safety margin: 240 × 13 × 0.8 = 2496W
  CIRCUIT_MAX_W: 2496,
  PRODUCT_DEFAULT: "Absen Hi-LED 55+ Pro P1.9 / equivalent P2.5",
  COMPANY_NAME: "PROFOUND",
  PANELS_PER_FLIGHTCASE: 10,
  POWERLINK_PER_CASE: 10,
  DATALINK_PER_CASE: 10,
  POWERSTART_10M_PER_CASE: 1,
  POWERSTART_1M_PER_CASE: 1,
  DATASTART_KIT_PER_CASE: 2,
  ETAPE_PER_CASE: 1,
  FITKIT_PER_CASE: 10,
  NEUTRIK_COUPLER_FIXED: 4,
  LED_SPARES_PCT: 0.1,
};

export type Config = typeof CONFIG;
