import { useState, useRef, useEffect } from "react";

// ── Colors ────────────────────────────────────────────────────────────────────
const PORT_COLORS = [
  "#2563EB", "#059669", "#7C3AED", "#0891B2",
  "#0D9488", "#4F46E5", "#1D4ED8", "#047857",
];

const CHAIN_COLORS = [
  "#DC2626", "#EA580C", "#D97706", "#CA8A04",
  "#92400E", "#BE185D", "#B45309", "#9F1239",
];

// ── Layout constants (SVG user units) ────────────────────────────────────────
const GRID_W = 540;
const CALLOUT_TOP = 46;
const CALLOUT_R = 80;
const CAPTION_H = 40;
const CALLOUT_COLOR = "#D63025";
const TICK_HALF = 7;
const LABEL_GAP = 11;
const PANEL_STROKE = "#B8C8DC";
const GRID_BORDER = "#8BA3C0";
const CAPTION_COLOR = "#718096";

type EntryEdge = "top" | "bottom" | "left" | "right";
type Snapshot = { data: Record<string, number[]>; power: Record<string, number[]> };

interface Props {
  columns: number;
  rows: number;
  widthM: number;
  heightM: number;
  panelWidthMm: number;
  panelHeightMm: number;
  pixelPitch: string;
  activePanels: number;
  numPorts: number;
  panelsPerPort: number;
  panelPowerW: number;
  powerSizingMode: "operating" | "max";
  onPowerSizingModeChange: (m: "operating" | "max") => void;
  routingMode: "layout" | "data" | "power";
  cableEntry: EntryEdge;
  dataPortSequences: Record<string, number[]>;
  powerChainSequences: Record<string, number[]>;
  powerMaxWatts: number;
  onModeChange: (m: "layout" | "data" | "power") => void;
  onCableEntryChange: (e: EntryEdge) => void;
  onDataPortSequencesChange: (s: Record<string, number[]>) => void;
  onPowerChainSequencesChange: (s: Record<string, number[]>) => void;
  onPowerMaxWattsChange: (w: number) => void;
}

// ── Pure helpers ──────────────────────────────────────────────────────────────

function hexToRgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r},${g},${b},${alpha})`;
}

/**
 * Practical traversal order for power chains.
 * Bottom/top entry → column-major serpentine (vertical runs up/down columns).
 * Left/right entry → row-major serpentine (horizontal runs).
 * Each chain starting panel is always at the entry edge.
 */
function buildPracticalOrder(entry: EntryEdge, cols: number, rws: number): number[] {
  const order: number[] = [];
  if (entry === "bottom" || entry === "top") {
    for (let c = 0; c < cols; c++) {
      const goUp = entry === "bottom" ? c % 2 === 0 : c % 2 !== 0;
      if (goUp) {
        for (let r = rws - 1; r >= 0; r--) order.push(r * cols + c);
      } else {
        for (let r = 0; r < rws; r++) order.push(r * cols + c);
      }
    }
  } else {
    for (let r = 0; r < rws; r++) {
      const goRight = entry === "left" ? r % 2 === 0 : r % 2 !== 0;
      if (goRight) {
        for (let c = 0; c < cols; c++) order.push(r * cols + c);
      } else {
        for (let c = cols - 1; c >= 0; c--) order.push(r * cols + c);
      }
    }
  }
  return order;
}

/** Fill each chain to capacity; last chain gets the remainder. */
function buildAutoChains(panelsPerChain: number, order: number[]): Record<string, number[]> {
  const seqs: Record<string, number[]> = {};
  let chainNum = 1;
  let batch: number[] = [];
  for (const idx of order) {
    batch.push(idx);
    if (batch.length >= panelsPerChain) {
      seqs[String(chainNum++)] = batch;
      batch = [];
    }
  }
  if (batch.length > 0) seqs[String(chainNum)] = batch;
  return seqs;
}

// ── Component ─────────────────────────────────────────────────────────────────

export function CableRoutingGrid({
  columns,
  rows,
  widthM,
  heightM,
  panelWidthMm,
  panelHeightMm,
  pixelPitch,
  activePanels,
  numPorts,
  panelsPerPort,
  panelPowerW,
  powerSizingMode,
  onPowerSizingModeChange,
  routingMode,
  cableEntry,
  dataPortSequences,
  powerChainSequences,
  powerMaxWatts,
  onModeChange,
  onCableEntryChange,
  onDataPortSequencesChange,
  onPowerChainSequencesChange,
}: Props) {
  const svgRef = useRef<SVGSVGElement>(null);

  // ── UI state ─────────────────────────────────────────────────────────────
  const [activePort, setActivePort] = useState(1);
  const [activeChain, setActiveChain] = useState(1);
  const [numChains, setNumChains] = useState(2);
  const [isDragging, setIsDragging] = useState(false);
  const [lastTouchedPanel, setLastTouchedPanel] = useState<number | null>(null);
  const [flashPanel, setFlashPanel] = useState<number | null>(null);
  const [portFullWarning, setPortFullWarning] = useState<number | null>(null);
  const [portFullPos, setPortFullPos] = useState<{ x: number; y: number } | null>(null);

  // ── Undo/redo ─────────────────────────────────────────────────────────────
  const [undoStack, setUndoStack] = useState<Snapshot[]>([]);
  const [redoStack, setRedoStack] = useState<Snapshot[]>([]);

  // ── Auto-generate tracking (power only) ──────────────────────────────────
  const [powerAutoGenerated, setPowerAutoGenerated] = useState(false);
  const [showModeChangeWarning, setShowModeChangeWarning] = useState(false);
  const pendingRegenRef = useRef(false);

  // ── Selection state ───────────────────────────────────────────────────────
  const [selectedPanels, setSelectedPanels] = useState<Set<number>>(new Set());
  const [isSelectDrag, setIsSelectDrag] = useState(false);

  // ── Refs ──────────────────────────────────────────────────────────────────
  const isDraggingRef = useRef(false);
  useEffect(() => { isDraggingRef.current = isDragging; }, [isDragging]);

  // One undo push per drag stroke (not per panel)
  const dragUndoPushed = useRef(false);

  // ── Reset history when grid dimensions change (new project) ──────────────
  useEffect(() => {
    setUndoStack([]);
    setRedoStack([]);
    setSelectedPanels(new Set());
    setPowerAutoGenerated(false);
    setShowModeChangeWarning(false);
  }, [columns, rows]);

  // ── Regenerate auto chains after panelPowerW updates ─────────────────────
  useEffect(() => {
    if (!pendingRegenRef.current) return;
    pendingRegenRef.current = false;
    const ppc = Math.max(1, Math.floor(powerMaxWatts / panelPowerW));
    const order = buildPracticalOrder(cableEntry, columns, rows);
    const newSeqs = buildAutoChains(ppc, order);
    const count = Object.keys(newSeqs).length;
    setNumChains(Math.max(1, count));
    // Push undo before overwriting — capture current sequences
    setUndoStack(prev => [
      ...prev.slice(-49),
      { data: dataPortSequences, power: powerChainSequences },
    ]);
    setRedoStack([]);
    setPowerAutoGenerated(true);
    setShowModeChangeWarning(false);
    onPowerChainSequencesChange(newSeqs);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [panelPowerW]);

  // ── Keyboard shortcuts ────────────────────────────────────────────────────
  useEffect(() => {
    if (routingMode !== "data" && routingMode !== "power") return;

    function onKeyDown(e: KeyboardEvent) {
      const el = document.activeElement as HTMLElement | null;
      if (el && (el.tagName === "INPUT" || el.tagName === "TEXTAREA" || el.isContentEditable)) return;

      if ((e.metaKey || e.ctrlKey) && (e.key === "z" || e.key === "Z")) {
        e.preventDefault();
        if (e.shiftKey) handleRedo();
        else handleUndo();
        return;
      }
      if (e.ctrlKey && e.key === "y") {
        e.preventDefault();
        handleRedo();
        return;
      }
      if ((e.key === "Delete" || e.key === "Backspace") && selectedPanels.size > 0) {
        e.preventDefault();
        handleDeleteSelected();
        return;
      }
      if (e.key === "Escape") {
        setSelectedPanels(new Set());
      }
    }

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  // Re-register when any of these change so closures are fresh
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [routingMode, selectedPanels, undoStack, redoStack, dataPortSequences, powerChainSequences]);

  // Global mouseup (in case user releases outside SVG)
  useEffect(() => {
    function onWindowMouseUp() {
      if (isDraggingRef.current) {
        setIsDragging(false);
        setLastTouchedPanel(null);
        setIsSelectDrag(false);
      }
    }
    window.addEventListener("mouseup", onWindowMouseUp);
    return () => window.removeEventListener("mouseup", onWindowMouseUp);
  }, []);

  // ── SVG geometry ──────────────────────────────────────────────────────────
  if (columns <= 0 || rows <= 0) return null;

  const cellW = GRID_W / columns;
  const cellH = cellW;
  const gridH = cellH * rows;
  const totalW = GRID_W + CALLOUT_R;
  const totalH = CALLOUT_TOP + gridH + CAPTION_H;
  const gx = 0;
  const gy = CALLOUT_TOP;
  const widthLineY = gy - CALLOUT_TOP / 2;
  const heightLineX = gx + GRID_W + 22;

  // ── Reverse maps: panel → port / chain ───────────────────────────────────
  const panelToPort: Record<number, number> = {};
  Object.entries(dataPortSequences).forEach(([portKey, indices]) => {
    const portNum = parseInt(portKey, 10);
    indices.forEach((idx) => { panelToPort[idx] = portNum; });
  });

  const panelToChain: Record<number, number> = {};
  Object.entries(powerChainSequences).forEach(([chainKey, indices]) => {
    const chainNum = parseInt(chainKey, 10);
    indices.forEach((idx) => { panelToChain[idx] = chainNum; });
  });

  // ── Panel center coords ───────────────────────────────────────────────────
  function panelCenter(idx: number): { cx: number; cy: number } {
    const col = idx % columns;
    const row = Math.floor(idx / columns);
    return {
      cx: gx + col * cellW + cellW / 2,
      cy: gy + row * cellH + cellH / 2,
    };
  }

  // ── Client coords → panel index ───────────────────────────────────────────
  // Uses SVG's own coordinate transform so that scaling, preserveAspectRatio
  // letterboxing/pillarboxing, and CSS transforms are all handled correctly.
  function clientToPanel(e: { clientX: number; clientY: number }): number | null {
    const svg = svgRef.current;
    if (!svg) return null;
    const ctm = svg.getScreenCTM();
    if (!ctm) return null;
    const pt = svg.createSVGPoint();
    pt.x = e.clientX;
    pt.y = e.clientY;
    const { x: vx, y: vy } = pt.matrixTransform(ctm.inverse());
    if (vx < gx || vx >= gx + GRID_W || vy < gy || vy >= gy + gridH) return null;
    const col = Math.floor((vx - gx) / cellW);
    const row = Math.floor((vy - gy) / cellH);
    if (col < 0 || col >= columns || row < 0 || row >= rows) return null;
    return row * columns + col;
  }

  // ── Undo / Redo ───────────────────────────────────────────────────────────
  function pushUndo() {
    setUndoStack(prev => [
      ...prev.slice(-49),
      { data: dataPortSequences, power: powerChainSequences },
    ]);
    setRedoStack([]);
  }

  function handleUndo() {
    if (undoStack.length === 0) return;
    const snap = undoStack[undoStack.length - 1];
    setRedoStack(s => [...s.slice(-49), { data: dataPortSequences, power: powerChainSequences }]);
    setUndoStack(s => s.slice(0, -1));
    onDataPortSequencesChange(snap.data);
    onPowerChainSequencesChange(snap.power);
    const powerKeys = Object.keys(snap.power).map(Number);
    if (powerKeys.length > 0) setNumChains(Math.max(2, Math.max(...powerKeys)));
    setSelectedPanels(new Set());
  }

  function handleRedo() {
    if (redoStack.length === 0) return;
    const snap = redoStack[redoStack.length - 1];
    setUndoStack(s => [...s.slice(-49), { data: dataPortSequences, power: powerChainSequences }]);
    setRedoStack(s => s.slice(0, -1));
    onDataPortSequencesChange(snap.data);
    onPowerChainSequencesChange(snap.power);
    const powerKeys = Object.keys(snap.power).map(Number);
    if (powerKeys.length > 0) setNumChains(Math.max(2, Math.max(...powerKeys)));
    setSelectedPanels(new Set());
  }

  // ── Chain removal ─────────────────────────────────────────────────────────
  function removeChain(chainNum: number) {
    pushUndo();
    const newSeqs: Record<string, number[]> = {};
    let newNum = 1;
    for (let ch = 1; ch <= numChains; ch++) {
      if (ch === chainNum) continue;
      newSeqs[String(newNum++)] = powerChainSequences[String(ch)] ?? [];
    }
    const newCount = newNum - 1;
    setNumChains(Math.max(1, newCount));
    setActiveChain(prev => Math.min(prev, Math.max(1, newCount)));
    onPowerChainSequencesChange(newSeqs);
    setPowerAutoGenerated(false);
  }

  // ── Delete selected panels ────────────────────────────────────────────────
  function handleDeleteSelected() {
    if (selectedPanels.size === 0) return;
    pushUndo();
    if (routingMode === "data") {
      const newSeqs: Record<string, number[]> = {};
      Object.entries(dataPortSequences).forEach(([k, panels]) => {
        newSeqs[k] = panels.filter(p => !selectedPanels.has(p));
      });
      onDataPortSequencesChange(newSeqs);
    } else if (routingMode === "power") {
      const newSeqs: Record<string, number[]> = {};
      Object.entries(powerChainSequences).forEach(([k, panels]) => {
        newSeqs[k] = panels.filter(p => !selectedPanels.has(p));
      });
      onPowerChainSequencesChange(newSeqs);
    }
    setSelectedPanels(new Set());
  }

  // ── Auto-chain generation (power) ─────────────────────────────────────────
  function runAutoChains() {
    pushUndo();
    const ppc = Math.max(1, Math.floor(powerMaxWatts / panelPowerW));
    const order = buildPracticalOrder(cableEntry, columns, rows);
    const newSeqs = buildAutoChains(ppc, order);
    const count = Object.keys(newSeqs).length;
    setNumChains(Math.max(1, count));
    onPowerChainSequencesChange(newSeqs);
    setPowerAutoGenerated(true);
    setShowModeChangeWarning(false);
  }

  // ── Power sizing mode switch ──────────────────────────────────────────────
  function handlePowerSizingModeChange(m: "operating" | "max") {
    const hasChains = Object.values(powerChainSequences).some(c => c.length > 0);
    if (hasChains) {
      if (powerAutoGenerated) {
        pendingRegenRef.current = true;
      } else {
        setShowModeChangeWarning(true);
      }
    }
    onPowerSizingModeChange(m);
  }

  // ── Draw: add panel to active port ───────────────────────────────────────
  function addPanelToPort(panelIdx: number, e?: { clientX: number; clientY: number }) {
    if (!dragUndoPushed.current) { pushUndo(); dragUndoPushed.current = true; }
    const portKey = String(activePort);
    const existingPort = panelToPort[panelIdx];
    if (existingPort === activePort) return;
    const currentSeq = dataPortSequences[portKey] ?? [];
    if (currentSeq.length >= panelsPerPort) {
      setPortFullWarning(activePort);
      if (e) setPortFullPos({ x: e.clientX, y: e.clientY });
      setTimeout(() => setPortFullWarning(null), 1200);
      return;
    }
    const newSeqs = { ...dataPortSequences };
    if (existingPort !== undefined) {
      newSeqs[String(existingPort)] = (newSeqs[String(existingPort)] ?? []).filter(i => i !== panelIdx);
      setFlashPanel(panelIdx);
      setTimeout(() => setFlashPanel(null), 300);
    }
    if (!newSeqs[portKey]) newSeqs[portKey] = [];
    if (!newSeqs[portKey].includes(panelIdx)) {
      newSeqs[portKey] = [...newSeqs[portKey], panelIdx];
    }
    onDataPortSequencesChange(newSeqs);
  }

  // ── Draw: add panel to active chain ──────────────────────────────────────
  function addPanelToChain(panelIdx: number, e?: { clientX: number; clientY: number }) {
    if (!dragUndoPushed.current) { pushUndo(); dragUndoPushed.current = true; }
    const chainKey = String(activeChain);
    const panelsPerChain = Math.max(1, Math.floor(powerMaxWatts / panelPowerW));
    const existingChain = panelToChain[panelIdx];
    if (existingChain === activeChain) return;
    const currentSeq = powerChainSequences[chainKey] ?? [];
    if (currentSeq.length >= panelsPerChain) {
      setPortFullWarning(activeChain);
      if (e) setPortFullPos({ x: e.clientX, y: e.clientY });
      setTimeout(() => setPortFullWarning(null), 1200);
      return;
    }
    const newSeqs = { ...powerChainSequences };
    if (existingChain !== undefined) {
      newSeqs[String(existingChain)] = (newSeqs[String(existingChain)] ?? []).filter(i => i !== panelIdx);
      setFlashPanel(panelIdx);
      setTimeout(() => setFlashPanel(null), 300);
    }
    if (!newSeqs[chainKey]) newSeqs[chainKey] = [];
    if (!newSeqs[chainKey].includes(panelIdx)) {
      newSeqs[chainKey] = [...newSeqs[chainKey], panelIdx];
    }
    onPowerChainSequencesChange(newSeqs);
    setPowerAutoGenerated(false);
  }

  // ── Mouse / touch handlers ────────────────────────────────────────────────
  function startInteraction(idx: number, e?: { clientX: number; clientY: number }) {
    dragUndoPushed.current = false;
    const isAssigned = routingMode === "data"
      ? panelToPort[idx] !== undefined
      : panelToChain[idx] !== undefined;

    if (isAssigned) {
      setIsSelectDrag(true);
      setIsDragging(true);
      setLastTouchedPanel(idx);
      setSelectedPanels(new Set([idx]));
    } else {
      setIsSelectDrag(false);
      setIsDragging(true);
      setLastTouchedPanel(idx);
      setSelectedPanels(new Set());
      if (routingMode === "data") addPanelToPort(idx, e);
      else addPanelToChain(idx, e);
    }
  }

  function continueInteraction(idx: number, e?: { clientX: number; clientY: number }) {
    if (isSelectDrag) {
      const isAssigned = routingMode === "data"
        ? panelToPort[idx] !== undefined
        : panelToChain[idx] !== undefined;
      if (isAssigned) setSelectedPanels(prev => new Set([...prev, idx]));
    } else {
      if (routingMode === "data") addPanelToPort(idx, e);
      else addPanelToChain(idx, e);
    }
  }

  function handleMouseDown(e: React.MouseEvent<SVGSVGElement>) {
    if (routingMode !== "data" && routingMode !== "power") return;
    const idx = clientToPanel(e);
    if (idx === null) return;
    startInteraction(idx, e);
  }

  function handleMouseMove(e: React.MouseEvent<SVGSVGElement>) {
    if (!isDragging || (routingMode !== "data" && routingMode !== "power")) return;
    const idx = clientToPanel(e);
    if (idx === null || idx === lastTouchedPanel) return;
    setLastTouchedPanel(idx);
    continueInteraction(idx, e);
  }

  function handleMouseUp() {
    setIsDragging(false);
    setLastTouchedPanel(null);
    setIsSelectDrag(false);
  }

  function handleTouchStart(e: React.TouchEvent<SVGSVGElement>) {
    if (routingMode !== "data" && routingMode !== "power") return;
    e.preventDefault();
    const t = e.touches[0];
    const idx = clientToPanel(t);
    if (idx === null) return;
    startInteraction(idx, t);
  }

  function handleTouchMove(e: React.TouchEvent<SVGSVGElement>) {
    if (!isDragging || (routingMode !== "data" && routingMode !== "power")) return;
    e.preventDefault();
    const t = e.touches[0];
    const idx = clientToPanel(t);
    if (idx === null || idx === lastTouchedPanel) return;
    setLastTouchedPanel(idx);
    continueInteraction(idx, t);
  }

  function handleTouchEnd() {
    setIsDragging(false);
    setLastTouchedPanel(null);
    setIsSelectDrag(false);
  }

  // ── Data routing auto algorithms (unchanged) ──────────────────────────────
  function serpentineForEntry(entry: EntryEdge): number[] {
    const order: number[] = [];
    if (entry === "top") {
      for (let r = 0; r < rows; r++) {
        if (r % 2 === 0) for (let c = 0; c < columns; c++) order.push(r * columns + c);
        else for (let c = columns - 1; c >= 0; c--) order.push(r * columns + c);
      }
    } else if (entry === "bottom") {
      for (let r = rows - 1; r >= 0; r--) {
        const ri = rows - 1 - r;
        if (ri % 2 === 0) for (let c = 0; c < columns; c++) order.push(r * columns + c);
        else for (let c = columns - 1; c >= 0; c--) order.push(r * columns + c);
      }
    } else if (entry === "left") {
      for (let c = 0; c < columns; c++) {
        if (c % 2 === 0) for (let r = 0; r < rows; r++) order.push(r * columns + c);
        else for (let r = rows - 1; r >= 0; r--) order.push(r * columns + c);
      }
    } else {
      for (let c = columns - 1; c >= 0; c--) {
        const ci = columns - 1 - c;
        if (ci % 2 === 0) for (let r = 0; r < rows; r++) order.push(r * columns + c);
        else for (let r = rows - 1; r >= 0; r--) order.push(r * columns + c);
      }
    }
    return order;
  }

  function autoEvenSplit(): Record<string, number[]> {
    const total = columns * rows;
    const use = Math.min(numPorts, Math.max(Math.ceil(total / panelsPerPort), numPorts));
    const base = Math.floor(total / use);
    const extra = total % use;
    const order = serpentineForEntry(cableEntry);
    const seqs: Record<string, number[]> = {};
    let idx = 0;
    for (let p = 1; p <= use; p++) {
      seqs[String(p)] = order.slice(idx, idx + base + (p <= extra ? 1 : 0));
      idx += seqs[String(p)].length;
    }
    return seqs;
  }

  function autoRowAligned(): Record<string, number[]> {
    const seqs: Record<string, number[]> = {};
    const orderedRows = cableEntry === "bottom"
      ? Array.from({ length: rows }, (_, i) => rows - 1 - i)
      : Array.from({ length: rows }, (_, i) => i);

    function portPanels(portRows: number[]): number[] {
      const panels: number[] = [];
      portRows.forEach((r, idx) => {
        const ltr = cableEntry === "right" ? idx % 2 !== 0 : idx % 2 === 0;
        if (ltr) for (let c = 0; c < columns; c++) panels.push(r * columns + c);
        else for (let c = columns - 1; c >= 0; c--) panels.push(r * columns + c);
      });
      return panels;
    }

    if (orderedRows.length <= numPorts) {
      orderedRows.forEach((r, i) => { seqs[String(i + 1)] = portPanels([r]); });
    } else {
      const base = Math.floor(rows / numPorts);
      const extra = rows % numPorts;
      let ri = 0;
      for (let p = 1; p <= numPorts; p++) {
        const nr = base + (p <= extra ? 1 : 0);
        seqs[String(p)] = portPanels(orderedRows.slice(ri, ri + nr));
        ri += nr;
      }
    }
    return seqs;
  }

  function autoColumnAligned(): Record<string, number[]> {
    const seqs: Record<string, number[]> = {};
    const use = Math.min(numPorts, columns);
    const base = Math.floor(columns / use);
    const extra = columns % use;
    const orderedCols = cableEntry === "right"
      ? Array.from({ length: columns }, (_, i) => columns - 1 - i)
      : Array.from({ length: columns }, (_, i) => i);

    function portPanels(portCols: number[]): number[] {
      const panels: number[] = [];
      portCols.forEach((col, idx) => {
        const goUp = cableEntry === "bottom" ? idx % 2 === 0 : idx % 2 !== 0;
        if (goUp) for (let r = rows - 1; r >= 0; r--) panels.push(r * columns + col);
        else for (let r = 0; r < rows; r++) panels.push(r * columns + col);
      });
      return panels;
    }

    let ci = 0;
    for (let p = 1; p <= use; p++) {
      const nc = base + (p <= extra ? 1 : 0);
      seqs[String(p)] = portPanels(orderedCols.slice(ci, ci + nc));
      ci += nc;
    }
    return seqs;
  }

  function autoMinimumPorts(): Record<string, number[]> {
    const order = serpentineForEntry(cableEntry);
    const seqs: Record<string, number[]> = {};
    let port = 1;
    for (const idx of order) {
      if (port > numPorts) break;
      while (port <= numPorts) {
        const k = String(port);
        if (!seqs[k]) seqs[k] = [];
        if (seqs[k].length < panelsPerPort) { seqs[k].push(idx); break; }
        port++;
      }
    }
    return seqs;
  }

  // ── Render helpers ────────────────────────────────────────────────────────
  function renderCableLines(sequences: Record<string, number[]>, colors: string[], markerId: string) {
    return Object.entries(sequences).flatMap(([key, indices]) => {
      const num = parseInt(key, 10);
      const color = colors[(num - 1) % colors.length];
      if (indices.length < 2) return [];
      const points = indices.map(idx => panelCenter(idx));
      const d = points.map((p, i) => `${i === 0 ? "M" : "L"} ${p.cx} ${p.cy}`).join(" ");
      return [
        <path
          key={`line-${key}`}
          d={d}
          fill="none"
          stroke={color}
          strokeWidth={2}
          strokeOpacity={0.8}
          markerEnd={`url(#${markerId}-${num})`}
        />,
      ];
    });
  }

  function renderFirstPanelMarkers(sequences: Record<string, number[]>, colors: string[]) {
    return Object.entries(sequences).flatMap(([key, indices]) => {
      if (indices.length === 0) return [];
      const num = parseInt(key, 10);
      const color = colors[(num - 1) % colors.length];
      const { cx, cy } = panelCenter(indices[0]);
      const r = Math.min(cellW, cellH) * 0.22;
      return [
        <circle key={`marker-${key}`} cx={cx} cy={cy} r={r} fill={color} />,
        <text
          key={`marker-text-${key}`}
          x={cx} y={cy}
          textAnchor="middle"
          dominantBaseline="central"
          fontSize={r * 1.1}
          fontFamily="system-ui,sans-serif"
          fontWeight="700"
          fill="white"
        >
          {num}
        </text>,
      ];
    });
  }

  function renderMarkers(sequences: Record<string, number[]>, colors: string[], markerId: string) {
    return Object.entries(sequences).map(([key]) => {
      const num = parseInt(key, 10);
      const color = colors[(num - 1) % colors.length];
      return (
        <marker
          key={`marker-def-${markerId}-${num}`}
          id={`${markerId}-${num}`}
          markerWidth={6} markerHeight={6}
          refX={5} refY={3}
          orient="auto"
        >
          <path d="M0,0 L0,6 L6,3 z" fill={color} fillOpacity={0.8} />
        </marker>
      );
    });
  }

  // ── Totals ────────────────────────────────────────────────────────────────
  const assignedDataPanels = Object.values(dataPortSequences).flat().length;
  const unassignedDataPanels = activePanels - assignedDataPanels;
  const totalDataCapacity = numPorts * panelsPerPort;
  const assignedChainPanels = Object.values(powerChainSequences).flat().length;
  const totalChainWatts = assignedChainPanels * panelPowerW;
  const hasUndo = undoStack.length > 0;
  const hasRedo = redoStack.length > 0;

  return (
    <div className="space-y-3">
      {/* ── Mode toggle ──────────────────────────────────────────────────── */}
      <div className="flex gap-1">
        {(["layout", "data", "power"] as const).map((m) => (
          <button
            key={m}
            onClick={() => onModeChange(m)}
            className={`text-xs px-3 py-1.5 rounded font-medium transition-colors ${
              routingMode === m
                ? "bg-blue-600 text-white"
                : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"
            }`}
          >
            {m === "layout" ? "Layout" : m === "data" ? "Data routing" : "Power routing"}
          </button>
        ))}
      </div>

      {/* ── Cable entry side selector ─────────────────────────────────────── */}
      {(routingMode === "data" || routingMode === "power") && (
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs text-gray-500 dark:text-gray-400">Cable entry:</span>
          {([
            { edge: "bottom" as EntryEdge, label: "↑ Bottom", title: "Processor at floor" },
            { edge: "top"    as EntryEdge, label: "↓ Top",    title: "Processor above wall" },
            { edge: "left"   as EntryEdge, label: "→ Left",   title: "Processor to the left" },
            { edge: "right"  as EntryEdge, label: "← Right",  title: "Processor to the right" },
          ]).map(({ edge, label, title }) => (
            <button
              key={edge}
              title={title}
              onClick={() => onCableEntryChange(edge)}
              className={`text-xs px-2.5 py-1 rounded transition-colors ${
                cableEntry === edge
                  ? "bg-red-600 text-white font-medium"
                  : "border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
              }`}
            >
              {label}
            </button>
          ))}
        </div>
      )}

      {/* ── Port selector (data mode) ─────────────────────────────────────── */}
      {routingMode === "data" && (
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs text-gray-500 dark:text-gray-400">Port:</span>
          {Array.from({ length: numPorts }, (_, i) => i + 1).map((p) => {
            const color = PORT_COLORS[(p - 1) % PORT_COLORS.length];
            return (
              <button
                key={p}
                onClick={() => setActivePort(p)}
                style={{
                  backgroundColor: color,
                  outline: activePort === p ? "2px solid white" : undefined,
                  outlineOffset: activePort === p ? "2px" : undefined,
                  boxShadow: activePort === p ? `0 0 0 3px ${color}` : undefined,
                }}
                className="w-7 h-7 rounded text-white text-xs font-bold transition-all"
              >
                {p}
              </button>
            );
          })}
        </div>
      )}

      {/* ── Chain selector (power mode) ──────────────────────────────────── */}
      {routingMode === "power" && (
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-xs text-gray-500 dark:text-gray-400">Chain:</span>
          {Array.from({ length: numChains }, (_, i) => i + 1).map((ch) => {
            const color = CHAIN_COLORS[(ch - 1) % CHAIN_COLORS.length];
            return (
              <div key={ch} className="relative group">
                <button
                  onClick={() => setActiveChain(ch)}
                  style={{
                    backgroundColor: color,
                    outline: activeChain === ch ? "2px solid white" : undefined,
                    outlineOffset: activeChain === ch ? "2px" : undefined,
                    boxShadow: activeChain === ch ? `0 0 0 3px ${color}` : undefined,
                  }}
                  className="w-7 h-7 rounded text-white text-xs font-bold transition-all"
                >
                  {ch}
                </button>
                {/* Remove button — appears on hover */}
                <button
                  onClick={(e) => { e.stopPropagation(); removeChain(ch); }}
                  title={`Remove chain ${ch}`}
                  className="absolute -top-1.5 -right-1.5 w-4 h-4 rounded-full bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 text-gray-500 dark:text-gray-400 text-[9px] font-bold leading-none items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity hidden group-hover:flex hover:bg-red-100 dark:hover:bg-red-900/40 hover:text-red-600 dark:hover:text-red-400 hover:border-red-300"
                >
                  ×
                </button>
              </div>
            );
          })}
          <button
            onClick={() => { setNumChains(n => n + 1); }}
            className="text-xs px-2 py-1 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
          >
            +Add chain
          </button>
        </div>
      )}

      {/* ── Action buttons — data mode ─────────────────────────────────────── */}
      {routingMode === "data" && (
        <div className="flex gap-1.5 flex-wrap items-center">
          <button
            onClick={() => { pushUndo(); onDataPortSequencesChange({}); }}
            className="text-xs px-3 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
          >
            Clear
          </button>
          <button
            disabled={!hasUndo}
            onClick={handleUndo}
            title="Undo (Ctrl/Cmd+Z)"
            className="text-xs px-2 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-30"
          >
            ↩
          </button>
          <button
            disabled={!hasRedo}
            onClick={handleRedo}
            title="Redo (Ctrl/Cmd+Shift+Z)"
            className="text-xs px-2 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-30"
          >
            ↪
          </button>
          <span className="text-xs text-gray-400 dark:text-gray-500 ml-1">Auto:</span>
          <button
            title="Row strips — one port per row or grouped rows. Clean horizontal cable runs."
            onClick={() => { pushUndo(); onDataPortSequencesChange(autoRowAligned()); }}
            className="text-xs px-3 py-1.5 rounded bg-blue-600 text-white hover:bg-blue-700 font-medium"
          >
            Row strips
          </button>
          <button
            title="Even split — balanced panel count across all ports, may cross row boundaries."
            onClick={() => { pushUndo(); onDataPortSequencesChange(autoEvenSplit()); }}
            className="text-xs px-3 py-1.5 rounded bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 text-blue-700 dark:text-blue-300 hover:bg-blue-100 dark:hover:bg-blue-900/40"
          >
            Even split
          </button>
          <button
            title="Column strips — one port per column or grouped columns."
            onClick={() => { pushUndo(); onDataPortSequencesChange(autoColumnAligned()); }}
            className="text-xs px-3 py-1.5 rounded bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 text-blue-700 dark:text-blue-300 hover:bg-blue-100 dark:hover:bg-blue-900/40"
          >
            Col strips
          </button>
          <button
            title="Min ports — fills each port to maximum capacity before starting the next."
            onClick={() => { pushUndo(); onDataPortSequencesChange(autoMinimumPorts()); }}
            className="text-xs px-3 py-1.5 rounded bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 text-blue-700 dark:text-blue-300 hover:bg-blue-100 dark:hover:bg-blue-900/40"
          >
            Min ports
          </button>
        </div>
      )}

      {/* ── Action buttons — power mode ────────────────────────────────────── */}
      {routingMode === "power" && (
        <div className="space-y-2">
          <div className="flex gap-2 flex-wrap items-center">
            <button
              onClick={() => { pushUndo(); onPowerChainSequencesChange({}); setNumChains(2); setPowerAutoGenerated(false); setShowModeChangeWarning(false); }}
              className="text-xs px-3 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800"
            >
              Clear
            </button>
            <button
              disabled={!hasUndo}
              onClick={handleUndo}
              title="Undo (Ctrl/Cmd+Z)"
              className="text-xs px-2 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-30"
            >
              ↩
            </button>
            <button
              disabled={!hasRedo}
              onClick={handleRedo}
              title="Redo (Ctrl/Cmd+Shift+Z)"
              className="text-xs px-2 py-1.5 rounded border border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800 disabled:opacity-30"
            >
              ↪
            </button>
            <button
              title="Auto-assign power chains — fills each chain to capacity using a practical cable run from the entry edge."
              onClick={runAutoChains}
              className="text-xs px-3 py-1.5 rounded bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-700 text-red-700 dark:text-red-300 hover:bg-red-100 dark:hover:bg-red-900/40"
            >
              Auto chains
            </button>
          </div>

          {/* Mode-change warning (manual chains exist, mode switched) */}
          {showModeChangeWarning && (
            <div className="flex items-center gap-2 px-3 py-2 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700 rounded-lg text-xs text-amber-700 dark:text-amber-300">
              <span>⚠ Power mode changed — manually drawn chains may exceed the new per-chain limit.</span>
              <button
                onClick={runAutoChains}
                className="ml-auto shrink-0 px-2 py-1 rounded bg-amber-100 dark:bg-amber-900/40 border border-amber-300 dark:border-amber-600 hover:bg-amber-200 dark:hover:bg-amber-900/60 font-medium"
              >
                Re-run auto chains
              </button>
              <button
                onClick={() => setShowModeChangeWarning(false)}
                className="text-amber-500 hover:text-amber-700 dark:hover:text-amber-200"
              >
                ×
              </button>
            </div>
          )}
        </div>
      )}

      {/* Selection hint */}
      {(routingMode === "data" || routingMode === "power") && selectedPanels.size > 0 && (
        <div className="flex items-center gap-2 px-3 py-1.5 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-700 rounded text-xs text-blue-700 dark:text-blue-300">
          <span>{selectedPanels.size} panel{selectedPanels.size !== 1 ? "s" : ""} selected — press Delete to unassign</span>
          <button onClick={() => setSelectedPanels(new Set())} className="ml-auto text-blue-400 hover:text-blue-600">✕</button>
        </div>
      )}

      {/* ── SVG grid ──────────────────────────────────────────────────────── */}
      <div className="relative">
        <svg
          ref={svgRef}
          viewBox={`0 0 ${totalW} ${totalH}`}
          className="w-full h-auto select-none"
          aria-label="Cable routing grid"
          style={{
            maxHeight: 520,
            cursor: (routingMode === "data" || routingMode === "power")
              ? (isDragging ? "crosshair" : "pointer")
              : "default",
          }}
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onTouchStart={handleTouchStart}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
        >
          <defs>
            {renderMarkers(dataPortSequences, PORT_COLORS, "port-arrow")}
            {renderMarkers(powerChainSequences, CHAIN_COLORS, "chain-arrow")}
            <style>{`
              @keyframes panel-flash {
                0%   { opacity: 0.8; }
                100% { opacity: 0; }
              }
              .panel-flash-rect { animation: panel-flash 0.3s ease-out forwards; }
            `}</style>
          </defs>

          {/* ── Panel cells ───────────────────────────────────────────── */}
          {Array.from({ length: rows }, (_, r) =>
            Array.from({ length: columns }, (_, c) => {
              const idx = r * columns + c;
              let fill = "#EBF0F8";
              if (routingMode === "data") {
                const ap = panelToPort[idx];
                fill = ap !== undefined ? hexToRgba(PORT_COLORS[(ap - 1) % PORT_COLORS.length], 0.25) : "#E2E8F0";
              } else if (routingMode === "power") {
                const ac = panelToChain[idx];
                fill = ac !== undefined ? hexToRgba(CHAIN_COLORS[(ac - 1) % CHAIN_COLORS.length], 0.25) : "#E2E8F0";
              }
              return (
                <rect
                  key={idx}
                  x={gx + c * cellW}
                  y={gy + r * cellH}
                  width={cellW}
                  height={cellH}
                  fill={fill}
                  stroke={PANEL_STROKE}
                  strokeWidth={0.75}
                />
              );
            })
          )}

          {/* ── Grid outer border ─────────────────────────────────────── */}
          <rect x={gx} y={gy} width={GRID_W} height={gridH} fill="none" stroke={GRID_BORDER} strokeWidth={1} />

          {/* ── FRONT VIEW label ──────────────────────────────────────── */}
          <text x={gx + 6} y={gy + 14} fontSize={8} fontFamily="system-ui,sans-serif" fill="#94A3B8" letterSpacing={0.5}>
            FRONT VIEW
          </text>

          {/* ── Cable lines ───────────────────────────────────────────── */}
          {routingMode === "data" && renderCableLines(dataPortSequences, PORT_COLORS, "port-arrow")}
          {routingMode === "power" && renderCableLines(powerChainSequences, CHAIN_COLORS, "chain-arrow")}

          {/* ── First-panel markers ───────────────────────────────────── */}
          {routingMode === "data" && renderFirstPanelMarkers(dataPortSequences, PORT_COLORS)}
          {routingMode === "power" && renderFirstPanelMarkers(powerChainSequences, CHAIN_COLORS)}

          {/* ── Selection highlight ───────────────────────────────────── */}
          {(routingMode === "data" || routingMode === "power") && [...selectedPanels].map(idx => {
            const c = idx % columns;
            const r = Math.floor(idx / columns);
            return (
              <rect
                key={`sel-${idx}`}
                x={gx + c * cellW + 1}
                y={gy + r * cellH + 1}
                width={cellW - 2}
                height={cellH - 2}
                fill="none"
                stroke="white"
                strokeWidth={1.5}
                strokeDasharray="3,2"
                style={{ pointerEvents: "none" }}
              />
            );
          })}

          {/* ── Flash overlay ─────────────────────────────────────────── */}
          {flashPanel !== null && (() => {
            const c = flashPanel % columns;
            const r = Math.floor(flashPanel / columns);
            return (
              <rect
                className="panel-flash-rect"
                x={gx + c * cellW} y={gy + r * cellH}
                width={cellW} height={cellH}
                fill="white"
                style={{ pointerEvents: "none" }}
              />
            );
          })()}

          {/* ── Width callout ─────────────────────────────────────────── */}
          <line x1={gx} y1={widthLineY - TICK_HALF} x2={gx} y2={widthLineY + TICK_HALF} stroke={CALLOUT_COLOR} strokeWidth={1.5} />
          <line x1={gx + GRID_W} y1={widthLineY - TICK_HALF} x2={gx + GRID_W} y2={widthLineY + TICK_HALF} stroke={CALLOUT_COLOR} strokeWidth={1.5} />
          <line x1={gx} y1={widthLineY} x2={gx + GRID_W} y2={widthLineY} stroke={CALLOUT_COLOR} strokeWidth={1.5} />
          <text x={gx + GRID_W / 2} y={widthLineY - LABEL_GAP} textAnchor="middle" fontSize={11} fontFamily="system-ui,sans-serif" fontWeight="600" fill={CALLOUT_COLOR}>
            {`${widthM.toFixed(3)} m`}
          </text>

          {/* ── Height callout ────────────────────────────────────────── */}
          <line x1={heightLineX - 8} y1={gy} x2={heightLineX + 8} y2={gy} stroke={CALLOUT_COLOR} strokeWidth={1.5} />
          <line x1={heightLineX - 8} y1={gy + gridH} x2={heightLineX + 8} y2={gy + gridH} stroke={CALLOUT_COLOR} strokeWidth={1.5} />
          <line x1={heightLineX} y1={gy} x2={heightLineX} y2={gy + gridH} stroke={CALLOUT_COLOR} strokeWidth={1.5} />
          <text x={heightLineX + LABEL_GAP} y={gy + gridH / 2} textAnchor="start" dominantBaseline="middle" fontSize={11} fontFamily="system-ui,sans-serif" fontWeight="600" fill={CALLOUT_COLOR}>
            {`${heightM.toFixed(3)} m`}
          </text>

          {/* ── Cable entry indicator ─────────────────────────────────── */}
          {(routingMode === "data" || routingMode === "power") && (() => {
            const EC = CALLOUT_COLOR;
            const entryLabels: Record<EntryEdge, string> = {
              bottom: "↑ CABLE ENTRY — BOTTOM",
              top:    "↓ CABLE ENTRY — TOP",
              left:   "→ CABLE ENTRY — LEFT",
              right:  "← CABLE ENTRY — RIGHT",
            };
            const stripe = {
              bottom: <rect key="es" x={gx} y={gy + gridH - 3} width={GRID_W} height={3} fill={EC} opacity={0.45} />,
              top:    <rect key="es" x={gx} y={gy} width={GRID_W} height={3} fill={EC} opacity={0.45} />,
              left:   <rect key="es" x={gx} y={gy} width={3} height={gridH} fill={EC} opacity={0.45} />,
              right:  <rect key="es" x={gx + GRID_W - 3} y={gy} width={3} height={gridH} fill={EC} opacity={0.45} />,
            }[cableEntry];
            return (
              <>
                {stripe}
                <text x={gx + GRID_W / 2} y={gy + gridH + 13} textAnchor="middle" fontSize={8} fontFamily="system-ui,sans-serif" fontWeight="600" fill={EC}>
                  {entryLabels[cableEntry]}
                </text>
              </>
            );
          })()}

          {/* ── Caption ───────────────────────────────────────────────── */}
          <text x={gx} y={gy + gridH + 30} fontSize={10} fontFamily="system-ui,sans-serif" fill={CAPTION_COLOR}>
            {`${columns} × ${rows} panels  ·  ${panelWidthMm} × ${panelHeightMm} mm per panel  ·  ${pixelPitch}  ·  ${activePanels} panels total`}
          </text>
        </svg>

        {/* ── Full-warning tooltip ──────────────────────────────────────── */}
        {portFullWarning !== null && portFullPos !== null && (
          <div
            className="fixed z-50 pointer-events-none bg-amber-100 dark:bg-amber-900 border border-amber-400 text-amber-800 dark:text-amber-200 text-xs px-2 py-1 rounded shadow"
            style={{ left: portFullPos.x + 12, top: portFullPos.y - 24 }}
          >
            {routingMode === "power"
              ? `Chain ${portFullWarning} full (${Math.max(1, Math.floor(powerMaxWatts / panelPowerW))} panels max)`
              : `Port ${portFullWarning} full (${panelsPerPort} panels max)`}
          </div>
        )}
      </div>

      {/* ── Port summary (data mode) ──────────────────────────────────────── */}
      {routingMode === "data" && (
        <div className="text-xs space-y-1 bg-gray-50 dark:bg-gray-800/50 rounded-lg p-3">
          {Array.from({ length: numPorts }, (_, i) => i + 1).map((p) => {
            const color = PORT_COLORS[(p - 1) % PORT_COLORS.length];
            const count = (dataPortSequences[String(p)] ?? []).length;
            const overLimit = count > panelsPerPort;
            return (
              <div key={p} className="flex items-center gap-2">
                <span style={{ color }} className="font-bold text-base leading-none">●</span>
                <span className={overLimit ? "text-amber-600 dark:text-amber-400 font-medium" : "text-gray-700 dark:text-gray-300"}>
                  Port {p}: {count} panels{overLimit ? " ⚠ over limit" : ""}
                </span>
              </div>
            );
          })}
          <div className="pt-1 border-t border-gray-200 dark:border-gray-700 text-gray-500 dark:text-gray-400">
            Total: {assignedDataPanels} / {totalDataCapacity} assigned · {unassignedDataPanels} unassigned
          </div>
          {hasUndo && (
            <div className="text-gray-400 dark:text-gray-500 pt-0.5">
              {undoStack.length} action{undoStack.length !== 1 ? "s" : ""} in history · ⌘Z / Ctrl+Z to undo
            </div>
          )}
        </div>
      )}

      {/* ── Chain summary (power mode) ────────────────────────────────────── */}
      {routingMode === "power" && (
        <div className="text-xs space-y-1 bg-gray-50 dark:bg-gray-800/50 rounded-lg p-3">
          <div className="flex items-center justify-between mb-2 pb-2 border-b border-gray-200 dark:border-gray-700">
            <span className="text-gray-500 dark:text-gray-400">Power sizing:</span>
            <div className="flex gap-1">
              {(["operating", "max"] as const).map((m) => (
                <button
                  key={m}
                  onClick={() => handlePowerSizingModeChange(m)}
                  title={m === "operating" ? `${panelPowerW} W/panel — typical content` : `${panelPowerW} W/panel — full white`}
                  className={`px-2 py-0.5 rounded text-xs transition-colors ${
                    powerSizingMode === m
                      ? m === "max"
                        ? "bg-amber-500 text-white font-medium"
                        : "bg-green-600 text-white font-medium"
                      : "border border-gray-300 dark:border-gray-600 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
                  }`}
                >
                  {m === "operating" ? "Operating" : "Max"}
                </button>
              ))}
            </div>
          </div>
          {Array.from({ length: numChains }, (_, i) => i + 1).map((ch) => {
            const color = CHAIN_COLORS[(ch - 1) % CHAIN_COLORS.length];
            const count = (powerChainSequences[String(ch)] ?? []).length;
            const watts = count * panelPowerW;
            const overBudget = watts > powerMaxWatts;
            return (
              <div key={ch} className="flex items-center gap-2">
                <span style={{ color }} className="font-bold text-base leading-none">●</span>
                <span className={overBudget ? "text-red-600 dark:text-red-400 font-medium" : "text-gray-700 dark:text-gray-300"}>
                  Chain {ch}: {count} panels · {watts} W{overBudget ? " ⚠ over budget" : ""}
                </span>
              </div>
            );
          })}
          <div className="pt-1 border-t border-gray-200 dark:border-gray-700 text-gray-500 dark:text-gray-400">
            Total: {assignedChainPanels} panels · {totalChainWatts} W ({powerSizingMode})
          </div>
          {hasUndo && (
            <div className="text-gray-400 dark:text-gray-500 pt-0.5">
              {undoStack.length} action{undoStack.length !== 1 ? "s" : ""} in history · ⌘Z / Ctrl+Z to undo
            </div>
          )}
        </div>
      )}
    </div>
  );
}
